apiVersion: v1
kind: ConfigMap
metadata:
  name: master-config
  namespace: config-master
  annotations:
    # Reflector annotation to reflect this ConfigMap to child namespaces
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "child-1,child-2,child-3,child-4"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
data:
  config.json: |
    {
      "port": 8080,
      "address": "0.0.0.0",
      "enabled": false
    }