apiVersion: v1
kind: Pod
metadata:
  name: config-reader-pod
  namespace: child-3
  labels:
    app: config-reader
spec:
  containers:
  - name: config-reader
    image: ember-reflector-lab:latest
    imagePullPolicy: IfNotPresent
    args:
      - "-config"
      - "/etc/config/config.json"
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
      readOnly: true
  volumes:
  - name: config-volume
    configMap:
      name: master-config
  restartPolicy: Always